### PR TITLE
Resolved issues

### PR DESCRIPTION
**Pull request by kimconcillado**
#8, 9, 10 and 12 have been resolved.

### CODE REVIEW

**Comment by kimconcillado** [comment]
@aaronbeekay does this revision warrant a change (v2.3)?

**Comment by aaronbeekay** [comment]
@kimconcillado Yeah, all of those issues are targeted for [v2.3](https://github.com/BuckeyeCurrent/BeagleBone-CAN-Backpack/milestones/v2.3). 

Are these commits all of the changes that you want to make for v2.3? If so, I'll review this for merging and mfg. If not, we can make a new branch on BuckeyeCurrent (v2.3), and you can file pull requests against that branch to break things up a little bit.

(In the future, I'll be trying to use option 2 more - more on this later.)

**Comment by kimconcillado** [comment]
@aaronbeekay please review it - it's all hte changes I want to make for v2.3. If all's well, I will edit the changelog, make the pdfs (how to use the new script?), etc

**Comment by kimconcillado** [comment]
idk how to unclose this

**Comment by aaronbeekay** [comment]
@kimconcillado Roger, will do.

**Comment by aaronbeekay** [comment]
@kimconcillado -

## Functionality 
* The LED circuit won't work as drawn. Q1 (and Q4, Q5, Q8) should be FDV301N (N-channel instead of P-channel FET): look at the drawing in [the issue](https://github.com/BuckeyeCurrent/BeagleBone-CAN-Backpack/issues/13#issuecomment-87484190) again.
image
* @sharrington93 - do you want the WAKE signal brought to two GPIO pins?
* The pins that control the LEDs (`GPIO1_13`, `EHRPWM2B`, `GPIO1_15`, `GPIO0_27`) are not connected to the BeagleBone. They need matching nets connected to the appropriate pins on P8, P9, etc. 
  * It might be more sensible to name the nets, e.g., "LED1_R_CTL" instead of "EHRPWM2B" (since that is their function).
* The `RXCAN` and `TXCAN` signals are still incorrect:
  * They are correct here:

image

  * but they need to be flipped here:

image

  * See [this discussion on current-tech](https://lists.osu.edu/mailman/private/current-tech/2015-February/001467.html), also referenced in issue #12.

## Standards issues
* The connectors named "LED1" and "LED2" should have names that match up to wiring harness connector names (X-###) – "LED1" and "LED2" should be their values.
* The connector named "X6" also needs a name that matches up to the vehicle wiring diagrams.
* Your changes to the "BEAGLEBONE_BLACK" device need to be merged into Component-libraries (commit them and make a pull request).
* The connectors on the board all need labels.
* Bottom silkscreen has the wrong version number.

## Feedback
* X-346 has a misleading value. It's called "12VPOWER" now, but its job is to *provide* power to the Rider Display LCD. I would probably rename it "LCD_POWER" or something like that.
* You connected the "WAKE" resistor divider to X-346 in the schematic. This doesn't make any difference electrically, but it implies that the connector is related to the WAKE circuit (which it isn't). It would be clearer if you left the WAKE circuit separate from other parts of the schematic, or if you tied it to the input connector (the CAN connector).

**Comment by sharrington93** [comment]
@aaronbeekay yes, please split wake into two separate pins just to make sure I can program in both sleep and wake. @kimconcillado I forgot to post my request on here last meeting about moving the wake GPIOs to GPIO set 0. If it's too late and too much hassle, don't worry about it. I believe I should be able to use any of the GPIOs.

**Comment by kimconcillado** [comment]
I can do that @sharrington93

**Comment by kimconcillado** [comment]
@aaronbeekay 
image We've decided to use 2 different connectors rather than one X-347. How should I proceed in naming them/should I work with @Victorb101

**Comment by aaronbeekay** [comment]
@kimconcillado You can modify that document and submit a pull request to that repository - but Victor may be able to help you faster.

**Comment by kimconcillado** [comment]
image
@aaronbeekay I picked another pin beside the first one. @sharrington93 can you describe moving the wake GPIOs to GPIO set 0 more? I'm not sure what that entails for the cape so Aaron might have to translate

**Comment by aaronbeekay** [comment]
@kimconcillado - one small request for consistency. Can you change the CAN connector, X-343, to the "DUAL-RA-SMD" package? That package is used on other boards across the team and it would simplify ordering.

**Comment by aaronbeekay** [comment]
Also, the BOM you have uploaded doesn't have costs or categories for most of the parts. Please include updates to partsdb.txt with the pull request you make for the BeagleBone part.

**Pull request merged**
